---
title: "Bonus checks"
output: html_document
---

# libraries

```{r}
library(rjson)
library(purrr)
library(tidyverse)
```

# Load data

```{r}
data_dir = "../raw_data/ex0"
cosub_parent_dir = "../mturk/ex0"
data_files = Sys.glob(paste(data_dir, '/*.json', sep=""))

df.graph_trials = data.frame()

graph_trials_to_df = function(list_data) {
  df = tibble::as_tibble(list_data[c("trial_type", "trial_index", "graph_trial_type", "trajectory", "keypresses", "keypress_rts", "keyups", "keyup_rts")])
  df$nodes_to_keys = rep(list(list_data$nodes_to_keys), nrow(df))
  return(df)
}

for (filename in data_files) {
  list.this_subject_data = fromJSON(file=filename)
  df.this_subject_data = graph_trials_to_df(list.this_subject_data[[5]]) %>%
    bind_rows(graph_trials_to_df(list.this_subject_data[[7]]))
  df.this_subject_data$subject_id = str_split(basename(filename), '\\.', simplify=T)[1, 1] 
  df.graph_trials = bind_rows(df.graph_trials, df.this_subject_data)
}
```

```{r}
df.graph_trials = df.graph_trials %>%
  rowwise() %>%
  mutate(target = ifelse(graph_trial_type == 'letter', 
                         list(nodes_to_keys[[trajectory+1]]),
                         list(nodes_to_keys[[trajectory+1]]))) %>%
  ungroup() %>%
  mutate(correct = map_int(keypresses, length) == map_int(target, length))
```

# assess performance by subject

```{r}
df.bonuses_full = df.graph_trials %>%
  group_by(subject_id) %>%
  summarize(pct_correct = mean(correct)) %>%
  mutate(bonus = pct_correct >= 0.88) %>% # being slightly lenient
  separate(subject_id, c("subject_id", "submission_time"))

```

```{r}
df.assignments = tibble()
for (res_file in Sys.glob(paste(cosub_parent_dir, '/*/production-results/*.json', sep=""))) {
  assignment_id = res_file %>%
    basename() %>%
    str_sub(0, -6) # remove .json
  this_result = fromJSON(file=res_file) 
  df.assignments = bind_rows(df.assignments,
                             tibble(subject_id=this_result$WorkerId, 
                                    res_file=res_file,
                                    assignment_id=assignment_id))
}
```

```{r}
df.bonuses_full = left_join(df.bonuses_full, df.assignments) %>% 
  mutate(bonus_amount = 2.00) %>%
  mutate(batch_num = map_chr(res_file, function(x) {str_split(x, "/")[[1]][4]}),
         condition = str_extract(batch_num, "[bcd]"),
         condition = ifelse(is.na(condition), 'a', condition)) 
df.bonuses_full
```
```{r}
df.bonuses = df.bonuses_full %>%
  filter(bonus)
```

# fixing stupid mistakes

```{r}
df_dictionary = read_csv(paste(data_dir, '/dictionary.csv', sep="")) %>%
  rename(numeric_subj_id = `index\\n`) %>%
  separate(filename, c("subject_id", "submission_time", "extension"))
```
```{r}
df_fix = df.bonuses_full %>% 
  left_join(df_dictionary)
```

```{r}
df_fix = df_fix %>%
  mutate(code = sprintf('"%i" ~ "%s"', numeric_subj_id, condition))
write_csv(df_fix %>%
            select(code),
          "../anonymized_data/ex0/subj_conds.csv")
```

