---
title: "Model analysis"
output: html_notebook
---


# Libraries

```{r}
library(tidyverse)
```

# data loading

```{r message=FALSE, warning=TRUE}
data_dir = "../modeling/results_repeated_symbols/"

files = Sys.glob(paste(data_dir, "*.csv", sep=""))

model_d = tibble()
for (f in files) {
  filename = basename(f)
  g1 = str_extract(filename, '(?<=g1)[a-z0-9_]+(?=_g2)')
  g2 = str_extract(filename, '(?<=g2)[a-z0-9_]+(?=_rs)')
  rs = str_extract(filename, '(?<=rs)\\d+')
  run = str_extract(filename, '(?<=run)\\d+')
  this_d = read_csv(f) %>%
    mutate(g1 = g1, g2 = g2, run = run)
  model_d = bind_rows(model_d, this_d)
}
```

## wrangling

```{r}
model_d = model_d %>%
  mutate(learning_first = step < max(step)/2,
         shifted_step = ifelse(learning_first,
                                step,
                                step - max(step)/2),
         relevant_loss = ifelse(learning_first,
                                loss1,
                                loss2),
         precursor = ifelse(learning_first,
                            "none",
                            g1),
         graph = ifelse(learning_first,
                        g1,
                        g2))
```

# Graphs (lol)
```{r}
theme_set(theme_classic())
```

```{r}
ggplot(model_d,
       aes(x=shifted_step, y=relevant_loss,
           color=precursor)) +
  geom_line(stat="summary",
            fun.y="mean") +
  facet_wrap(~graph) 
#ggsave("results/plots/modeling/minimal_transfer_shared.png", width=7, height=5)
```



